# Generated by Django 5.1.6 on 2025-03-02 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracker', '0003_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_allocation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=10)),
                ('milestone', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('workload', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('NOT STARTED', 'NOT STARTED'), ('IN PROGRESS', 'IN PROGRESS'), ('ON HOLD', 'ON HOLD'), ('COMPLETED', 'COMPLETED'), ('OVERDUE', 'OVERDUE')], default='NOT STARTED', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracker.project')),
            ],
        ),
    ]
